name: publish to github pages

on:
  push:
    # Trigger when there is a new commit on main branch
    branches: [ main ]
    # also trigger when a new release tag is added to the repo
    tags:
      - "v*"

# Cancel already running jobs
concurrency:
  group: publish_to_pages_${{ github.head_ref }}
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Publish website to Github Pages
            runner: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.setup_pages.outputs.base_url }}
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
    - name: Build website
      run: cargo run -p website
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Hack to fix upload-pages-artifact bug
      # see https://github.com/actions/deploy-pages/issues/383
      # without this fix, tagging a commit tagged as a release will silently skip the upload of the new website which includes the docs for the new tag.
      run: echo "GITHUB_SHA=$(LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 32 ; echo)" >> $GITHUB_ENV
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'website/root'
    - name: Deploy pages
      uses: actions/deploy-pages@v4
